# Site settings
title: Kiwook Lee`s HomePage
email: wook605@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wook0605.github.io" # the base hostname & protocol for your site

# Sidebar settings
description: wook605@gmaill.com      KangWon National University Student, Majoring Computer Engineering.

# Social icons
facebook: /cjsworldnr
linkedin: username
github: wook0605
deviantart: username
codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
