# Site settings
title: 이기욱의 블로그
email: wook605@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wook0605.github.io" # the base hostname & protocol for your site

# Sidebar settings
description: 강원대학교 삼척캠퍼스 에서 컴퓨터공학을 전공중임.

# Social icons
facebook: /cjsworldnr
github: wook0605

footer: © Taken theme

# Build settings
markdown: kramdown
